/*@
XOC Release License

Copyright (c) 2013-2014, Alibaba Group, All rights reserved.

    compiler@aliexpress.com

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Su Zhenyu nor the names of its contributors
      may be used to endorse or promote products derived from this software
      without specific prior written permission.

THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

author: Su Zhenyu
@*/
#ifndef __IR_TO_DEX_H__
#define __IR_TO_DEX_H__

#define CONT_toplirlist(s)                    (s)->top_level_irlist
#define CONT_epilogirlist(s)                  (s)->epilog_ir_list
class IR2D_CTX {
public:
	IR ** top_level_irlist; /*Top level of current ir list.
						Because the top level of ir list must be IR_ST or IR_IST.
						So store cannot be child node of IR.
						*/
	IR ** epilog_ir_list; /*Both of Post Dec/Inc will take side effects for base region
						So we must append the side effect ST operation followed, and
						record the side-effect ir as epilog of current statement.
						*/
};


class LAB2UINT : public
	HMap<LabelInfo const*, UINT, HashFuncBase2<LabelInfo const*> > {
public:
	LAB2UINT(UINT bsize = 0) :
		HMap<LabelInfo const*, UINT,
			HashFuncBase2<LabelInfo const*> >(bsize) {}
	virtual ~LAB2UINT() {}

	void set(LabelInfo const* li, UINT v)
	{ HMap<LabelInfo const*, UINT,
			HashFuncBase2<LabelInfo const*> >::set(li, ++v); }

	UINT get(LabelInfo const* li, bool * find)
	{ return HMap<LabelInfo const*, UINT,
			HashFuncBase2<LabelInfo const*> >::get(li, find) - 1; }
};


//Transformator from IR to LIR/DEX.
class IR2Dex {
protected:
	Region * m_ru;
	TypeMgr * m_dm;
	TypeIndexRep * m_tr;
	DexFile * m_df;
	SMemPool * m_pool;
	Dex2IR * m_d2ir;
	List<BackFillData*> m_bf_list;
	LAB2UINT m_lab2idx;
	Prno2UINT * m_org_pr2v; //Original map prno -> vreg generated by dex2ir.
	Prno2UINT * m_prno2v; //Map prno -> vreg after RA.
	VAR2UINT * m_var2blt;
	VAR2UINT * m_var2ofst;

	void * xmalloc(UINT size)
	{
		ASSERT(m_pool != NULL, ("need pool!!"));
		void * p = smpoolMalloc(size, m_pool);
		ASSERT0(p);
		memset(p, 0, size);
		return p;
	}

	//Use outside pool to alloc memory. The pool will
	//be freed by caller.
	void * _ymalloc(UINT size)
	{
		void * p = LIRMALLOC(size);
		ASSERT0(p);
		memset(p, 0, size);
		return p;
	}

public:
	IR2Dex(IN Region * ru, IN DexFile * df, IN Dex2IR * d2ir,
		   IN TypeIndexRep * tr, IN Prno2UINT * prno2v)
	{
		ASSERT0(ru && df && d2ir);
		m_ru = ru;
		m_df = df;
		m_dm = ru->get_dm();
		m_tr = tr;
		m_d2ir = d2ir;
		m_prno2v = prno2v;
		m_org_pr2v = m_d2ir->get_pr2v_map();
		ASSERT0(m_org_pr2v);
		m_var2blt = m_d2ir->get_var2blt_map();
		m_var2ofst = m_d2ir->get_var2ofst_map();
		m_lab2idx.init(getNearestPowerOf2(
						MAX(4, ru->get_bb_list()->get_elem_count())));
		m_pool = smpoolCreate(16, MEM_COMM);
	}

	~IR2Dex()
	{ smpoolDelete(m_pool); }

	LIR * buildCmpBias(IN IR ** ir);
	LIR * buildInstanceOf(IN IR ** ir);
	LIR * buildMove(IN IR ** ir);
	LIR * buildMonitorEnter(IN IR ** ir);
	LIR * buildMonitorExit(IN IR ** ir);
	LIR * buildArrayLength(IN IR ** ir);
	LIR * buildThrow(IN IR ** ir);
	LIR * buildMoveException(IN IR ** ir);
	LIR * buildMoveResult(IN IR ** ir);
	LIR * buildCheckCast(IN IR ** ir);
	LIR * buildConstClass(IN IR ** ir);
	LIR * buildFilledNewArray(IN IR ** ir);
	LIR * buildFillArrayData(IN IR ** ir);
	LIR * buildArray(IN IR ** ir);
	LIR * buildNewArray(IN IR ** ir);
	LIR * buildBinRegLit(IN IR ** ir);
	LIR * buildBinRegReg(IN IR ** ir);
	LIR * buildBinOp(IN IR ** ir);
	LIR * buildIget(IN IR ** ir);
	LIR * buildCvt(IN IR ** ir);
	LIR * buildConstString(IN IR ** ir);
	LIR * buildConst(IN IR ** ir);
	LIR * buildSget(IN IR ** ir);
	LIR * buildSgetBasicTypeVar(IN IR ** ir);
	LIR * buildSgetObj(IN IR ** ir);
	LIR * buildSput(IN IR ** ir);
	LIR * buildNewInstance(IN IR ** ir);
	LIR * buildInvoke(IN IR ** ir);
	LIR * buildUniOp(IN IR ** ir);

	LIR * convertSwitch(IN OUT IR ** ir, IN IR2D_CTX * cont);
	LIR * convertBranch(bool is_truebr, IN OUT IR ** ir, IN IR2D_CTX * cont);
	LIR * convertGoto(IN OUT IR ** ir, IN IR2D_CTX * cont);
	LIR * convertReturn(IN OUT IR ** ir, IN IR2D_CTX * cont);
	LIR * convertStoreVar(IN OUT IR ** ir, IN IR2D_CTX * cont);
	LIR * convertStorePR(IN OUT IR ** ir, IN IR2D_CTX * cont);
	LIR * convertStoreArray(IN OUT IR ** ir, IN IR2D_CTX * cont);
	LIR * convertIstore(IN OUT IR ** ir, IN IR2D_CTX * cont);
	LIR * convertCall(IN OUT IR ** ir, IN IR2D_CTX * cont);
	LIR * convertIcall(IN OUT IR ** ir, IN IR2D_CTX * cont);
	LIR * convert(IN OUT IR ** ir, IN IR2D_CTX * cont);
	void convert(IN IR * ir_list, OUT List<LIR*> & newlirs, Prno2UINT & prno2v);

	void dump_output(List<LIR*> & newlirs, Prno2UINT & prno2v);
	enum LIR_JDT_Kind get_lir_ty(DATA_TYPE dt);

	UINT findFieldId(IR * ir, IR * objptr);
	LAB2UINT * get_lab2idx() { return &m_lab2idx; }
	UINT get_vreg(UINT prno)
	{
		if (m_prno2v != NULL) {
			bool find;
			return m_prno2v->get(prno, &find);
		}
		ASSERT0(m_org_pr2v);
		return m_org_pr2v->get(prno);
	}

	UINT get_vreg(IR * pr)
	{
		ASSERT0(pr->is_pr());
		return get_vreg(PR_no(pr));
	}

	inline bool is_pair(IR const* ir)
	{ return m_dm->get_bytesize(IR_dt(ir))== 8; }
	bool is_builtin(IR const* ir, BLTIN_TYPE bt);
	void reloc();
};
#endif
